apiVersion: v1
kind: ConfigMap
metadata:
  name: cmu-springboot-config
  labels:
    app: cmu-springboot
    component: api
data:
  SERVER_PORT: "9090"
  POSTGRES_DB: "postgres"
  POSTGRES_USER: "postgres"
  SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres:5432/postgres"
  SPRING_DATASOURCE_DRIVER_CLASS_NAME: "org.postgresql.Driver"
  SPRING_JPA_HIBERNATE_DDL_AUTO: "update"
  SPRING_JPA_DATABASE_PLATFORM: "org.hibernate.dialect.PostgreSQLDialect"
  SPRINGDOC_SWAGGER_UI_PATH: "/swagger-ui.html"
