apiVersion: v1
kind: Secret
metadata:
  name: cmu-springboot-secret
  labels:
    app: cmu-springboot
    component: api
type: Opaque
stringData:
  SPRING_DATASOURCE_USERNAME: "postgres"
  SPRING_DATASOURCE_PASSWORD: "postgres"
  POSTGRES_PASSWORD: "postgres"
